### ISSUE TITLE
Example yaml files

### ISSUE THREAD

**Issue by karapalumbo21** [hkhanna/mistbat#19]
1. tx_match.yaml - Do you have an example of this? When I run the program it crashes because I don't have this file, and I don't know how to populate it.

2. tx_annotations.yaml - Do you have an example of this? Is it necessary?

3. manual_obs.yaml - Do you have an example of this? What is the expected format?

**Comment by hkhanna** [comment]
Ideally, these files would not be required. But since I threw this program together so quickly, I didn't bother to write the sensible checks to ignore these files if they're not present. Until someone (you?) fixes these bugs, the files need to be present with at least 1 entry for the program to work properly. 

I'll open a PR to provide examples for each of these three files.

**Comment by hkhanna** [comment]
@karapalumbo21 let me know if this gets you most of the way there. closing this issue for now.
